# Generated by Django 3.2.5 on 2021-09-07 08:21

import buildcorn.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.CharField(default=buildcorn.models.licenseid, max_length=50)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QualityLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('quality_type', models.CharField(default='Quality', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('quality_type', models.CharField(default='Safety', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('location', models.TextField()),
                ('typee', models.CharField(choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite')], max_length=10)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_approver', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ManyToManyField(blank=True, related_name='project_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=120)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('qid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildcorn.qualitylibrary')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildcorn.safetylibrary')),
            ],
        ),
    ]
