# Generated by Django 3.2.5 on 2021-09-25 05:08

import buildcorn.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(default=buildcorn.models.licenseid, max_length=20)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='employee_company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee_user')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.CharField(default=buildcorn.models.licenseid, max_length=50)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('boq_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('b_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('b_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_uom', models.CharField(max_length=10)),
                ('total_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(choices=[('Quality', 'Quality'), ('Safety', 'Safety')], max_length=10)),
                ('question_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('question', models.TextField()),
                ('admin_status', models.CharField(blank=True, choices=[('Valid', 'Valid'), ('InValid', 'InValid')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Compiled', 'Compiled'), ('Not Compiled', 'Not Compiled')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/page/%Y/%m/%d', verbose_name='Inspection pic')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.TextField()),
                ('supervisor_name', models.CharField(max_length=15)),
                ('supervisor_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('question', models.ManyToManyField(blank=True, to='buildcorn.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('question', models.ManyToManyField(blank=True, to='buildcorn.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('location', models.TextField()),
                ('inspection', models.CharField(blank=True, choices=[('D', 'Done'), ('P', 'Pending')], default='P', max_length=1, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_approver', to='buildcorn.employee')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
                ('employee', models.ManyToManyField(blank=True, related_name='project_employees', to='buildcorn.Employee')),
                ('material', models.ManyToManyField(blank=True, to='buildcorn.Material')),
                ('quality_checklist', models.ManyToManyField(blank=True, related_name='quality_checklists', to='buildcorn.QualityCheckList')),
                ('safety_checklist', models.ManyToManyField(blank=True, related_name='safety_checklists', to='buildcorn.SafetyCheckList')),
                ('vendors', models.ManyToManyField(blank=True, to='buildcorn.Vendor')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='material',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildcorn.vendor'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(default=buildcorn.models.licenseid, max_length=20)),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
