# Generated by Django 3.2.5 on 2021-09-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment_company_name'),
        ('buildcorn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
