# Generated by Django 3.2.5 on 2021-09-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otp_expiry'),
        ('buildcorn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='license_id',
        ),
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.AddField(
            model_name='license',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='tenure',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
