# Generated by Django 3.2.5 on 2021-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitylibrary',
            name='quality_type',
            field=models.CharField(choices=[('quality', 'Quality')], max_length=10),
        ),
        migrations.AlterField(
            model_name='safetylibrary',
            name='quality_type',
            field=models.CharField(choices=[('quality', 'Quality')], max_length=10),
        ),
    ]
