# Generated by Django 3.2.5 on 2021-09-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='checklist_id',
            new_name='question_id',
        ),
    ]
