# Generated by Django 3.2.5 on 2021-09-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='qid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildcorn.qualitylibrary'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildcorn.safetylibrary'),
        ),
        migrations.AlterField(
            model_name='qualitylibrary',
            name='quality_type',
            field=models.CharField(default='Quality', max_length=10),
        ),
        migrations.AlterField(
            model_name='safetylibrary',
            name='quality_type',
            field=models.CharField(default='Safety', max_length=10),
        ),
    ]
