# Generated by Django 3.2.5 on 2021-08-26 08:58

import buildcorn.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='qualitylibrary',
            name='quality_id',
            field=models.CharField(default=buildcorn.models.licenseid, max_length=30),
        ),
        migrations.AddField(
            model_name='safetylibrary',
            name='safety_id',
            field=models.CharField(default=buildcorn.models.licenseid, max_length=30),
        ),
        migrations.AddField(
            model_name='license',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildcorn.devicename'),
        ),
    ]
