# Generated by Django 3.2.5 on 2021-09-25 12:04

import buildcorn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0002_auto_20210925_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ven_id',
            field=models.CharField(blank=True, default=buildcorn.models.licenseid, max_length=30, null=True),
        ),
    ]
