# Generated by Django 3.2.5 on 2021-09-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0002_auto_20210901_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='text',
        ),
        migrations.AddField(
            model_name='checklist',
            name='question',
            field=models.TextField(default='Make your questions here'),
        ),
    ]
