# Generated by Django 3.2.5 on 2021-09-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0002_auto_20210904_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='qid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildcorn.qualitylibrary'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildcorn.safetylibrary'),
        ),
    ]
