# Generated by Django 3.2.5 on 2021-09-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0002_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inspection',
            field=models.CharField(blank=True, choices=[('D', 'Done'), ('P', 'Pending')], default='P', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
