# Generated by Django 3.2.5 on 2021-09-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0002_rename_checklist_id_question_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('Valid', 'Valid'), ('InValid', 'InValid')], max_length=10, null=True),
        ),
    ]
