# Generated by Django 3.2.5 on 2021-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0002_auto_20210826_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
