# Generated by Django 3.2.5 on 2021-09-27 08:49

import buildcorn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0003_vendor_ven_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mid',
            field=models.CharField(blank=True, default=buildcorn.models.licenseid, max_length=30, null=True),
        ),
    ]
