# Generated by Django 3.2.5 on 2021-09-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0003_question_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_approver', to='buildcorn.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='project_employees', to='buildcorn.Employee'),
        ),
    ]
