# Generated by Django 3.2.5 on 2021-09-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment_company_name'),
        ('buildcorn', '0003_auto_20210908_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
    ]
