# Generated by Django 3.2.5 on 2021-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0003_alter_license_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitylibrary',
            name='check_list',
            field=models.ManyToManyField(blank=True, to='buildcorn.CheckList'),
        ),
        migrations.AlterField(
            model_name='safetylibrary',
            name='check_list',
            field=models.ManyToManyField(blank=True, to='buildcorn.CheckList'),
        ),
    ]
