# Generated by Django 3.2.5 on 2021-09-24 05:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0004_auto_20210921_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=20)),
                ('boq_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('b_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('b_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('total_uom', models.CharField(max_length=10)),
                ('total_qty', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.TextField()),
                ('supervisor_name', models.CharField(max_length=15)),
                ('supervisor_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/page/%Y/%m/%d', verbose_name='Inspection pic'),
        ),
        migrations.AddField(
            model_name='project',
            name='material',
            field=models.ManyToManyField(blank=True, to='buildcorn.Material'),
        ),
        migrations.AddField(
            model_name='project',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='buildcorn.Vendor'),
        ),
    ]
