# Generated by Django 3.2.5 on 2021-09-28 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildcorn', '0004_material_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='buildcron_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_buildcron_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banner',
            name='tenent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_tenent_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
