# Generated by Django 3.2.5 on 2021-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0005_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitylibrary',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='safetylibrary',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='qualitylibrary',
            name='quality_type',
        ),
        migrations.RemoveField(
            model_name='qualitylibrary',
            name='status',
        ),
        migrations.RemoveField(
            model_name='safetylibrary',
            name='quality_type',
        ),
        migrations.RemoveField(
            model_name='safetylibrary',
            name='status',
        ),
        migrations.AddField(
            model_name='qualitylibrary',
            name='typee',
            field=models.CharField(blank=True, default='Quality', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='safetylibrary',
            name='typee',
            field=models.CharField(blank=True, default='Safety', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='answer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
