# Generated by Django 3.2.5 on 2021-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0005_auto_20210828_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
