# Generated by Django 3.2.5 on 2021-09-28 16:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0005_auto_20210928_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='multi_images',
            field=django_mysql.models.ListCharField(models.CharField(max_length=66), blank=True, max_length=300, null=True, size=4),
        ),
    ]
