# Generated by Django 3.2.5 on 2021-08-30 11:29

import buildcorn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0006_checklist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/merchendise/%Y/%m/%d')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.CharField(default=buildcorn.models.licenseid, max_length=50)),
                ('question', models.CharField(max_length=30)),
                ('answer', models.ImageField(upload_to='images/merchendise/%Y/%m/%d')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
