# Generated by Django 3.2.5 on 2021-09-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0006_auto_20210909_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='qid',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='sid',
        ),
        migrations.AddField(
            model_name='qualitylibrary',
            name='checklist',
            field=models.ManyToManyField(blank=True, to='buildcorn.CheckList'),
        ),
        migrations.AddField(
            model_name='safetylibrary',
            name='checklist',
            field=models.ManyToManyField(blank=True, to='buildcorn.CheckList'),
        ),
    ]
