# Generated by Django 3.2.5 on 2021-09-24 08:23

import buildcorn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0006_auto_20210924_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_id', models.CharField(default=buildcorn.models.licenseid, max_length=30)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='checklists',
        ),
        migrations.AddField(
            model_name='question',
            name='typee',
            field=models.CharField(choices=[('Quality', 'Quality'), ('Safety', 'Safety')], default='Quality', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CheckList',
        ),
        migrations.AddField(
            model_name='safetychecklist',
            name='question',
            field=models.ManyToManyField(blank=True, to='buildcorn.Question'),
        ),
        migrations.AddField(
            model_name='qualitychecklist',
            name='question',
            field=models.ManyToManyField(blank=True, to='buildcorn.Question'),
        ),
        migrations.AddField(
            model_name='project',
            name='quality_checklist',
            field=models.ManyToManyField(blank=True, related_name='quality_checklists', to='buildcorn.QualityCheckList'),
        ),
        migrations.AddField(
            model_name='project',
            name='safety_checklist',
            field=models.ManyToManyField(blank=True, related_name='safety_checklists', to='buildcorn.SafetyCheckList'),
        ),
    ]
