# Generated by Django 3.2.5 on 2021-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0007_banner_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
