# Generated by Django 3.2.5 on 2021-10-04 06:59

import buildcorn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0007_auto_20210929_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rid', models.CharField(blank=True, default=buildcorn.models.licenseid, max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('typee', models.CharField(max_length=10)),
                ('project', models.CharField(max_length=50)),
                ('submitted_by', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('download', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
