# Generated by Django 3.2.5 on 2021-09-14 11:39

import buildcorn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0008_auto_20210911_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(default=buildcorn.models.licenseid, max_length=20),
        ),
    ]
