# Generated by Django 3.2.5 on 2021-10-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0009_auto_20211004_1111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerchecklist',
            unique_together={('question', 'quality_checklist', 'safety_checklist')},
        ),
    ]
