# Generated by Django 3.2.5 on 2021-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0010_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='typee',
            field=models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite')], max_length=10, null=True),
        ),
    ]
