# Generated by Django 3.2.5 on 2021-10-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0010_alter_answerchecklist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchecklist',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildcorn.project'),
        ),
    ]
