# Generated by Django 3.2.5 on 2021-09-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0011_alter_project_typee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='phase',
        ),
    ]
