# Generated by Django 3.2.5 on 2021-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0012_auto_20210918_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='project_employees', to='buildcorn.Employee'),
        ),
    ]
