# Generated by Django 3.2.5 on 2021-10-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0012_auto_20211006_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchecklist',
            name='status',
            field=models.CharField(blank=True, choices=[('Complied', 'Complied'), ('Not Complied', 'Not Complied')], max_length=20, null=True),
        ),
    ]
