# Generated by Django 3.2.5 on 2021-10-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0013_alter_answerchecklist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('statement', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('Complied', 'Complied'), ('Not Complied', 'Not Complied')], max_length=15, null=True)),
                ('is_cleared', models.BooleanField(blank=True, default=False, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildcorn.vendor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildcorn.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildcorn.employee')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
