# Generated by Django 3.2.5 on 2021-10-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0014_siteobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteobservation',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='siteobservation/'),
        ),
    ]
