# Generated by Django 3.2.5 on 2021-10-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0015_siteobservation_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteobservation',
            name='reason_to_uncomplied',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Complied', 'Complied'), ('Not Complied', 'Not Complied')], max_length=15, null=True)),
                ('reason_to_uncomplied', models.TextField(blank=True, null=True)),
                ('area', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('root_cause', models.TextField()),
                ('root_cause_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recomended_action', models.TextField()),
                ('is_cleared', models.BooleanField(blank=True, default=False, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='NCR/')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildcorn.vendor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildcorn.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildcorn.employee')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
