# Generated by Django 3.2.5 on 2021-10-12 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildcorn', '0016_auto_20211008_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='tenent_user',
        ),
        migrations.CreateModel(
            name='TenentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenent_images', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='tenent_banner',
            field=models.ManyToManyField(blank=True, to='buildcorn.TenentBanner'),
        ),
    ]
