# Generated by Django 3.2.5 on 2021-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0017_auto_20211012_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='tenent_banner',
        ),
        migrations.AddField(
            model_name='tenentbanner',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
