# Generated by Django 3.2.5 on 2021-10-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_contactus_options'),
        ('buildcorn', '0018_auto_20211012_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenentbanner',
            name='user',
        ),
        migrations.AddField(
            model_name='tenentbanner',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
            preserve_default=False,
        ),
    ]
