# Generated by Django 3.2.5 on 2021-10-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0021_alter_approver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchecklist',
            name='shedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncr',
            name='reason_to_satiffaction_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncr',
            name='satiffaction_status',
            field=models.CharField(blank=True, choices=[('Complied', 'Complied'), ('Not Complied', 'Not Complied')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ncr',
            name='shedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteobservation',
            name='shedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildcorn.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='answerchecklist',
            name='site_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildcorn.sitedetails'),
        ),
    ]
