# Generated by Django 3.2.5 on 2021-10-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0022_auto_20211016_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchecklist',
            name='site_details',
        ),
        migrations.AddField(
            model_name='answerchecklist',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerchecklist',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildcorn.vendor'),
        ),
        migrations.DeleteModel(
            name='SiteDetails',
        ),
    ]
