# Generated by Django 3.2.5 on 2021-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0023_auto_20211016_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='emp_license_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
