# Generated by Django 3.2.5 on 2021-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0024_license_emp_license_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='last_license_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
