# Generated by Django 3.2.5 on 2021-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildcorn', '0025_license_last_license_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='license_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee license'),
        ),
    ]
