# Generated by Django 3.2.5 on 2021-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_addres_agent_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
