# Generated by Django 3.2.5 on 2021-08-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_lead_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
