# Generated by Django 3.2.5 on 2021-09-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='company',
            name='plan',
        ),
    ]
