# Generated by Django 3.2.5 on 2021-09-01 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
