# Generated by Django 3.2.5 on 2021-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_name',
        ),
        migrations.AddField(
            model_name='user',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DeviceName',
        ),
    ]
