# Generated by Django 3.2.5 on 2021-08-26 11:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210826_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=accounts.models.uniqueid, max_length=30),
        ),
    ]
