# Generated by Django 3.2.5 on 2021-09-24 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 24, 6, 26, 34, 642420, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
