# Generated by Django 3.2.5 on 2021-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.UUIDField(default=235945197483713),
        ),
    ]
