# Generated by Django 3.2.5 on 2021-09-07 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210907_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('IBNK', 'Internet Banking'), ('MBNK', 'Mobile Banking'), ('EWLT', 'Wallet'), ('DEBT', 'Debit card'), ('CRDT', 'Credit card'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('CHEK', 'Check')], max_length=4)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Done'), (2, 'Pending'), (3, 'Failed')], null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('due_amount', models.FloatField(blank=True, null=True)),
                ('pickup_type', models.CharField(choices=[('ONL', 'Online'), ('OFL', 'Offline')], max_length=3)),
                ('response', models.TextField(blank=True, max_length=1000, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_payments', to='accounts.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
