# Generated by Django 3.2.5 on 2021-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
