# Generated by Django 3.2.5 on 2021-09-24 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210924_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 24, 6, 33, 5, 136756, tzinfo=utc), null=True),
        ),
    ]
