# Generated by Django 3.2.5 on 2021-09-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
