# Generated by Django 3.2.5 on 2021-09-24 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210924_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 24, 9, 22, 15, 324830, tzinfo=utc), null=True),
        ),
    ]
