# Generated by Django 3.2.5 on 2021-09-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210901_0911'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.UUIDField(default=86939813658290),
        ),
    ]
