# Generated by Django 3.2.5 on 2021-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='holder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
