# Generated by Django 3.2.5 on 2021-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_payment_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_success',
        ),
        migrations.AddField(
            model_name='company',
            name='license_purchased',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='license_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Annual Plan', max_length=50),
        ),
    ]
