# Generated by Django 3.2.5 on 2021-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210903_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.UUIDField(default=106034141686359),
        ),
    ]
