# Generated by Django 3.2.5 on 2021-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_company_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
