# Generated by Django 3.2.5 on 2021-09-17 07:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiry', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 8, 4, 50, 930685, tzinfo=utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
