# Generated by Django 3.2.5 on 2021-09-17 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210917_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 11, 39, 11, 831901, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
