# Generated by Django 3.2.5 on 2021-09-17 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210917_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 11, 41, 5, 102247, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='validated',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
