# Generated by Django 3.2.5 on 2021-09-18 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210917_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 18, 7, 44, 40, 193800, tzinfo=utc), null=True),
        ),
    ]
